// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

    #include "lvgl.h"

#include "ui_helpers.h"
#include "components/ui_comp.h"
#include "components/ui_comp_hook.h"
#include "ui_events.h"
void console_desc1_anim_Animation( lv_obj_t *TargetObject, int delay);
void pressed_Animation( lv_obj_t *TargetObject, int delay);
void console_desc2_anim_Animation( lv_obj_t *TargetObject, int delay);
void clendar_anim_Animation( lv_obj_t *TargetObject, int delay);
void keyboardanim_Animation( lv_obj_t *TargetObject, int delay);
void FunctrlPanelanim_Animation( lv_obj_t *TargetObject, int delay);
void Turtlesimanim_Animation( lv_obj_t *TargetObject, int delay);
void Informationanim_Animation( lv_obj_t *TargetObject, int delay);
void MesgListanim_Animation( lv_obj_t *TargetObject, int delay);
void MesgTopicHanderanim_Animation( lv_obj_t *TargetObject, int delay);
void MsgConsoleanim_Animation( lv_obj_t *TargetObject, int delay);
void Subscriberanim_Animation( lv_obj_t *TargetObject, int delay);
void Publisheranim_Animation( lv_obj_t *TargetObject, int delay);
void TopicListanim_Animation( lv_obj_t *TargetObject, int delay);
void NodeListanim_Animation( lv_obj_t *TargetObject, int delay);
void SearchTopicanim_Animation( lv_obj_t *TargetObject, int delay);
void SearchNodeanim_Animation( lv_obj_t *TargetObject, int delay);
void informaanim_Animation( lv_obj_t *TargetObject, int delay);
void CloseImageanim_Animation( lv_obj_t *TargetObject, int delay);
// SCREEN: ui_start_menu
void ui_start_menu_screen_init(void);
extern lv_obj_t *ui_start_menu;
extern lv_obj_t *ui_rtt_logo;
void ui_event_console_name( lv_event_t * e);
extern lv_obj_t *ui_console_name;
extern lv_obj_t *ui_gui_describer;
void ui_event_ImgButton3( lv_event_t * e);
extern lv_obj_t *ui_ImgButton3;
extern lv_obj_t *ui_console_desc;
// SCREEN: ui_Main_Screen
void ui_Main_Screen_screen_init(void);
extern lv_obj_t *ui_Main_Screen;
extern lv_obj_t *ui_top_panel;
void ui_event_console2_desc( lv_event_t * e);
extern lv_obj_t *ui_console2_desc;
void ui_event_return_button( lv_event_t * e);
extern lv_obj_t *ui_return_button;
extern lv_obj_t *ui_wlan;
extern lv_obj_t *ui_battery;
void ui_event_calendar_label( lv_event_t * e);
extern lv_obj_t *ui_calendar_label;
extern lv_obj_t *ui_mesg_list_panel;
void ui_event_List_Topic_Dropdown( lv_event_t * e);
extern lv_obj_t *ui_List_Topic_Dropdown;
void ui_event_List_Node_Dropdown( lv_event_t * e);
extern lv_obj_t *ui_List_Node_Dropdown;
void ui_event_Search_Topic_TextArea( lv_event_t * e);
extern lv_obj_t *ui_Search_Topic_TextArea;
void ui_event_Search_Node_TextArea( lv_event_t * e);
extern lv_obj_t *ui_Search_Node_TextArea;
void ui_event_Subscriber_TextArea( lv_event_t * e);
extern lv_obj_t *ui_Subscriber_TextArea;
void ui_event_Pubscriber_TextArea( lv_event_t * e);
extern lv_obj_t *ui_Pubscriber_TextArea;
extern lv_obj_t *ui_mesg_handler;
extern lv_obj_t *ui_Console_Textarea;
extern lv_obj_t *ui_SubFunct_panel;
extern lv_obj_t *ui_SubTopicHander_Label;
void ui_event_SubFuncConfirm_Button( lv_event_t * e);
extern lv_obj_t *ui_SubFuncConfirm_Button;
extern lv_obj_t *ui_SubFuncWord_label;
void ui_event_CloseFigure1( lv_event_t * e);
extern lv_obj_t *ui_CloseFigure1;
extern lv_obj_t *ui_SubFuncConsole_panel;
extern lv_obj_t *ui_SubNodeName_label;
extern lv_obj_t *ui_SubMsgType_label;
extern lv_obj_t *ui_TopicName_label;
void ui_event_SubNodeName_textarea( lv_event_t * e);
extern lv_obj_t *ui_SubNodeName_textarea;
void ui_event_SubMsgType_textarea( lv_event_t * e);
extern lv_obj_t *ui_SubMsgType_textarea;
void ui_event_SubTopicNameMsg_textarea( lv_event_t * e);
extern lv_obj_t *ui_SubTopicNameMsg_textarea;
extern lv_obj_t *ui_PubFunct_panel;
extern lv_obj_t *ui_PubTopicHander_Label;
void ui_event_PubFuncConfirm_Button( lv_event_t * e);
extern lv_obj_t *ui_PubFuncConfirm_Button;
extern lv_obj_t *ui_PubFuncWord_label;
void ui_event_CloseFigure2( lv_event_t * e);
extern lv_obj_t *ui_CloseFigure2;
extern lv_obj_t *ui_PubFuncConsole_panel;
extern lv_obj_t *ui_PubNodeName_label;
extern lv_obj_t *ui_PubNodeID_label;
extern lv_obj_t *ui_PubTopicName_label;
void ui_event_PubNodeName_textarea( lv_event_t * e);
extern lv_obj_t *ui_PubNodeName_textarea;
void ui_event_PubNodeID_textarea( lv_event_t * e);
extern lv_obj_t *ui_PubNodeID_textarea;
void ui_event_PubTopicNameMsg_textarea( lv_event_t * e);
extern lv_obj_t *ui_PubTopicNameMsg_textarea;
extern lv_obj_t *ui_Func_Ctrl_Panel;
void ui_event_Func_Ctrl_label( lv_event_t * e);
extern lv_obj_t *ui_Func_Ctrl_label;
extern lv_obj_t *ui_Turtlesim_Demo_Panel;
void ui_event_Turtlesim_Demo_Label( lv_event_t * e);
extern lv_obj_t *ui_Turtlesim_Demo_Label;
extern lv_obj_t *ui_Turtlesim_background;
extern lv_obj_t *ui_Terminal_TextArea;
extern lv_obj_t *ui_Turtle_Figure;
extern lv_obj_t *ui_Terminal_Figure;
extern lv_obj_t *ui_Information_panel;
void ui_event_Information_label( lv_event_t * e);
extern lv_obj_t *ui_Information_label;
void ui_event_Keyboard( lv_event_t * e);
extern lv_obj_t *ui_Keyboard;
extern lv_obj_t *ui_Calendar;
extern lv_obj_t *ui_console_desc1;
extern lv_obj_t *ui_Information_TextArea;
void ui_event_Close_image( lv_event_t * e);
extern lv_obj_t *ui_Close_image;
extern lv_obj_t *ui____initial_actions0;

LV_IMG_DECLARE( ui_img_microros_rtt_png);   // assets\microros_rtt.png
LV_IMG_DECLARE( ui_img_startup_png);   // assets\startup.png
LV_IMG_DECLARE( ui_img_return_png);   // assets\return.png
LV_IMG_DECLARE( ui_img_serial_png);   // assets\Serial.png
LV_IMG_DECLARE( ui_img_1383021239);   // assets\battery-add.png
LV_IMG_DECLARE( ui_img_close_png);   // assets\close.png
LV_IMG_DECLARE( ui_img_tortle_background_png);   // assets\tortle_background.png
LV_IMG_DECLARE( ui_img_turtle_png);   // assets\Turtle.png
LV_IMG_DECLARE( ui_img_terminal_png);   // assets\terminal.png
LV_IMG_DECLARE( ui_img_1650958959);   // assets\battery-1.png
LV_IMG_DECLARE( ui_img_1915926208);   // assets\battery-2.png
LV_IMG_DECLARE( ui_img_close2_png);   // assets\close2.png



void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
