// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"


// COMPONENT next figure

lv_obj_t *ui_next_figure_create(lv_obj_t *comp_parent) {

lv_obj_t *cui_next_figure;
cui_next_figure = lv_img_create(comp_parent);
lv_img_set_src(cui_next_figure, &ui_img_startup_png);
lv_obj_set_width( cui_next_figure, LV_SIZE_CONTENT);  /// 48
lv_obj_set_height( cui_next_figure, LV_SIZE_CONTENT);   /// 48
lv_obj_set_x( cui_next_figure, -12 );
lv_obj_set_y( cui_next_figure, 83 );
lv_obj_set_align( cui_next_figure, LV_ALIGN_CENTER );
lv_obj_add_flag( cui_next_figure, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( cui_next_figure, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_NEXT_FIGURE_NUM);
children[UI_COMP_NEXT_FIGURE_NEXT_FIGURE] = cui_next_figure;
lv_obj_add_event_cb(cui_next_figure, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
lv_obj_add_event_cb(cui_next_figure, del_component_child_event_cb, LV_EVENT_DELETE, children);
ui_comp_next_figure_create_hook(cui_next_figure);
return cui_next_figure; 
}

