// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_Main_Screen_screen_init(void)
{
ui_Main_Screen = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Main_Screen, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Main_Screen, lv_color_hex(0x5F5F62), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Main_Screen, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_top_panel = lv_obj_create(ui_Main_Screen);
lv_obj_set_width( ui_top_panel, 482);
lv_obj_set_height( ui_top_panel, 28);
lv_obj_set_x( ui_top_panel, 1 );
lv_obj_set_y( ui_top_panel, -120 );
lv_obj_set_align( ui_top_panel, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_top_panel, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_top_panel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_top_panel, lv_color_hex(0x7C7474), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_top_panel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_top_panel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_blend_mode(ui_top_panel, LV_BLEND_MODE_MULTIPLY, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_opa(ui_top_panel, 50, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_console2_desc = lv_label_create(ui_Main_Screen);
lv_obj_set_width( ui_console2_desc, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_console2_desc, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_console2_desc, 2 );
lv_obj_set_y( ui_console2_desc, -120 );
lv_obj_set_align( ui_console2_desc, LV_ALIGN_CENTER );
lv_label_set_text(ui_console2_desc,"RT-MROS MonitorX");
lv_obj_add_flag( ui_console2_desc, LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_set_style_text_color(ui_console2_desc, lv_color_hex(0x0AE4F4), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_console2_desc, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_decor(ui_console2_desc, LV_TEXT_DECOR_UNDERLINE, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_return_button = lv_img_create(ui_Main_Screen);
lv_img_set_src(ui_return_button, &ui_img_return_png);
lv_obj_set_width( ui_return_button, LV_SIZE_CONTENT);  /// 32
lv_obj_set_height( ui_return_button, LV_SIZE_CONTENT);   /// 32
lv_obj_set_x( ui_return_button, -225 );
lv_obj_set_y( ui_return_button, -120 );
lv_obj_set_align( ui_return_button, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_return_button, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_return_button, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_grad_color(ui_return_button, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );

ui_wlan = lv_img_create(ui_Main_Screen);
lv_img_set_src(ui_wlan, &ui_img_serial_png);
lv_obj_set_width( ui_wlan, LV_SIZE_CONTENT);  /// 16
lv_obj_set_height( ui_wlan, LV_SIZE_CONTENT);   /// 16
lv_obj_set_x( ui_wlan, 208 );
lv_obj_set_y( ui_wlan, -122 );
lv_obj_set_align( ui_wlan, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_wlan, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_wlan, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_battery = lv_img_create(ui_Main_Screen);
lv_img_set_src(ui_battery, &ui_img_1383021239);
lv_obj_set_width( ui_battery, LV_SIZE_CONTENT);  /// 16
lv_obj_set_height( ui_battery, LV_SIZE_CONTENT);   /// 16
lv_obj_set_x( ui_battery, 229 );
lv_obj_set_y( ui_battery, -122 );
lv_obj_set_align( ui_battery, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_battery, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_battery, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_calendar_label = lv_label_create(ui_Main_Screen);
lv_obj_set_width( ui_calendar_label, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_calendar_label, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_calendar_label, 150 );
lv_obj_set_y( ui_calendar_label, -121 );
lv_obj_set_align( ui_calendar_label, LV_ALIGN_CENTER );
lv_label_set_text(ui_calendar_label,"     8:00\n2024/4/19");
lv_label_set_recolor(ui_calendar_label,"true");
lv_obj_add_flag( ui_calendar_label, LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_set_style_text_font(ui_calendar_label, &lv_font_montserrat_10, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_mesg_list_panel = lv_obj_create(ui_Main_Screen);
lv_obj_set_width( ui_mesg_list_panel, 103);
lv_obj_set_height( ui_mesg_list_panel, 199);
lv_obj_set_x( ui_mesg_list_panel, -187 );
lv_obj_set_y( ui_mesg_list_panel, -7 );
lv_obj_set_align( ui_mesg_list_panel, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_mesg_list_panel, LV_OBJ_FLAG_HIDDEN );   /// Flags
lv_obj_set_style_radius(ui_mesg_list_panel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_mesg_list_panel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_mesg_list_panel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_mesg_list_panel, lv_color_hex(0x1A3D25), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_mesg_list_panel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_mesg_list_panel, 2, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_List_Topic_Dropdown = lv_dropdown_create(ui_mesg_list_panel);
lv_dropdown_set_options( ui_List_Topic_Dropdown, "Topic 1\nTopic 2\nTopic 3\nTopic 4\nTopic 5\nTopic 6\nTopic 7\nTopic 8\nTopic 9" );
lv_dropdown_set_text( ui_List_Topic_Dropdown, "Topic List");
lv_obj_set_width( ui_List_Topic_Dropdown, 101);
lv_obj_set_height( ui_List_Topic_Dropdown, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_List_Topic_Dropdown, 0 );
lv_obj_set_y( ui_List_Topic_Dropdown, -79 );
lv_obj_set_align( ui_List_Topic_Dropdown, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_List_Topic_Dropdown, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_set_style_text_color(ui_List_Topic_Dropdown, lv_color_hex(0x02FD40), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_List_Topic_Dropdown, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_List_Topic_Dropdown, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_decor(ui_List_Topic_Dropdown, LV_TEXT_DECOR_UNDERLINE, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_List_Topic_Dropdown, &lv_font_montserrat_12, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_radius(ui_List_Topic_Dropdown, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_List_Topic_Dropdown, lv_color_hex(0x5F5F62), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_List_Topic_Dropdown, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_List_Topic_Dropdown, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_List_Topic_Dropdown, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_List_Topic_Dropdown, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_List_Topic_Dropdown, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_List_Topic_Dropdown, 15, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_List_Topic_Dropdown, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_List_Topic_Dropdown, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_List_Topic_Dropdown, 10, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_text_decor(ui_List_Topic_Dropdown, LV_TEXT_DECOR_UNDERLINE, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_List_Topic_Dropdown, &lv_font_montserrat_12, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_text_color(lv_dropdown_get_list(ui_List_Topic_Dropdown), lv_color_hex(0x020202),  LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(lv_dropdown_get_list(ui_List_Topic_Dropdown), 255,  LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(lv_dropdown_get_list(ui_List_Topic_Dropdown), LV_TEXT_ALIGN_CENTER,  LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(lv_dropdown_get_list(ui_List_Topic_Dropdown), &lv_font_montserrat_12,  LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_radius(lv_dropdown_get_list(ui_List_Topic_Dropdown), 0,  LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(lv_dropdown_get_list(ui_List_Topic_Dropdown), lv_color_hex(0xACA0A0),  LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(lv_dropdown_get_list(ui_List_Topic_Dropdown), 255,  LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(lv_dropdown_get_list(ui_List_Topic_Dropdown), 1,  LV_PART_MAIN| LV_STATE_DEFAULT);

ui_List_Node_Dropdown = lv_dropdown_create(ui_mesg_list_panel);
lv_dropdown_set_options( ui_List_Node_Dropdown, "Node 1\nNode 2\nNode 3\nNode 4\nNode 5\nNode 6\nNode 7\nNode 8\nNode 9" );
lv_dropdown_set_text( ui_List_Node_Dropdown, "Node List");
lv_obj_set_width( ui_List_Node_Dropdown, 101);
lv_obj_set_height( ui_List_Node_Dropdown, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_List_Node_Dropdown, 0 );
lv_obj_set_y( ui_List_Node_Dropdown, -42 );
lv_obj_set_align( ui_List_Node_Dropdown, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_List_Node_Dropdown, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_set_style_text_color(ui_List_Node_Dropdown, lv_color_hex(0x02FD40), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_List_Node_Dropdown, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_List_Node_Dropdown, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_decor(ui_List_Node_Dropdown, LV_TEXT_DECOR_UNDERLINE, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_List_Node_Dropdown, &lv_font_montserrat_12, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_radius(ui_List_Node_Dropdown, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_List_Node_Dropdown, lv_color_hex(0x5F5F62), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_List_Node_Dropdown, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_List_Node_Dropdown, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_List_Node_Dropdown, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_List_Node_Dropdown, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_List_Node_Dropdown, LV_BORDER_SIDE_FULL, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_List_Node_Dropdown, 15, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_List_Node_Dropdown, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_List_Node_Dropdown, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_List_Node_Dropdown, 10, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_text_decor(ui_List_Node_Dropdown, LV_TEXT_DECOR_UNDERLINE, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_List_Node_Dropdown, &lv_font_montserrat_12, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_text_color(lv_dropdown_get_list(ui_List_Node_Dropdown), lv_color_hex(0x020202),  LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(lv_dropdown_get_list(ui_List_Node_Dropdown), 255,  LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(lv_dropdown_get_list(ui_List_Node_Dropdown), LV_TEXT_ALIGN_CENTER,  LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(lv_dropdown_get_list(ui_List_Node_Dropdown), &lv_font_montserrat_12,  LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_radius(lv_dropdown_get_list(ui_List_Node_Dropdown), 0,  LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(lv_dropdown_get_list(ui_List_Node_Dropdown), lv_color_hex(0xACA0A0),  LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(lv_dropdown_get_list(ui_List_Node_Dropdown), 255,  LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(lv_dropdown_get_list(ui_List_Node_Dropdown), 1,  LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Search_Topic_TextArea = lv_textarea_create(ui_mesg_list_panel);
lv_obj_set_width( ui_Search_Topic_TextArea, 101);
lv_obj_set_height( ui_Search_Topic_TextArea, LV_SIZE_CONTENT);   /// 39
lv_obj_set_x( ui_Search_Topic_TextArea, 0 );
lv_obj_set_y( ui_Search_Topic_TextArea, -5 );
lv_obj_set_align( ui_Search_Topic_TextArea, LV_ALIGN_CENTER );
lv_textarea_set_placeholder_text(ui_Search_Topic_TextArea,"Search Topic");
lv_textarea_set_one_line(ui_Search_Topic_TextArea,true);
lv_obj_set_style_text_color(ui_Search_Topic_TextArea, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Search_Topic_TextArea, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_Search_Topic_TextArea, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Search_Topic_TextArea, &lv_font_montserrat_12, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_radius(ui_Search_Topic_TextArea, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Search_Topic_TextArea, lv_color_hex(0x5F5F62), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Search_Topic_TextArea, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Search_Topic_TextArea, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Search_Topic_TextArea, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Search_Topic_TextArea, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_Search_Topic_TextArea, LV_BORDER_SIDE_FULL, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_Search_Topic_TextArea, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_Search_Topic_TextArea, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_Search_Topic_TextArea, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_Search_Topic_TextArea, 10, LV_PART_MAIN| LV_STATE_DEFAULT);



ui_Search_Node_TextArea = lv_textarea_create(ui_mesg_list_panel);
lv_obj_set_width( ui_Search_Node_TextArea, 101);
lv_obj_set_height( ui_Search_Node_TextArea, LV_SIZE_CONTENT);   /// 39
lv_obj_set_x( ui_Search_Node_TextArea, 0 );
lv_obj_set_y( ui_Search_Node_TextArea, 32 );
lv_obj_set_align( ui_Search_Node_TextArea, LV_ALIGN_CENTER );
lv_textarea_set_placeholder_text(ui_Search_Node_TextArea,"Search Node");
lv_textarea_set_one_line(ui_Search_Node_TextArea,true);
lv_obj_set_style_text_color(ui_Search_Node_TextArea, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Search_Node_TextArea, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_Search_Node_TextArea, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Search_Node_TextArea, &lv_font_montserrat_12, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_radius(ui_Search_Node_TextArea, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Search_Node_TextArea, lv_color_hex(0x5F5F62), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Search_Node_TextArea, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Search_Node_TextArea, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Search_Node_TextArea, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Search_Node_TextArea, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_Search_Node_TextArea, LV_BORDER_SIDE_FULL, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_Search_Node_TextArea, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_Search_Node_TextArea, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_Search_Node_TextArea, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_Search_Node_TextArea, 10, LV_PART_MAIN| LV_STATE_DEFAULT);



ui_Subscriber_TextArea = lv_textarea_create(ui_mesg_list_panel);
lv_obj_set_width( ui_Subscriber_TextArea, 101);
lv_obj_set_height( ui_Subscriber_TextArea, LV_SIZE_CONTENT);   /// 39
lv_obj_set_x( ui_Subscriber_TextArea, 0 );
lv_obj_set_y( ui_Subscriber_TextArea, 69 );
lv_obj_set_align( ui_Subscriber_TextArea, LV_ALIGN_CENTER );
lv_textarea_set_placeholder_text(ui_Subscriber_TextArea,"Subscriber");
lv_textarea_set_one_line(ui_Subscriber_TextArea,true);
lv_obj_clear_flag( ui_Subscriber_TextArea, LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_text_color(ui_Subscriber_TextArea, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Subscriber_TextArea, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_Subscriber_TextArea, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Subscriber_TextArea, &lv_font_montserrat_12, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_radius(ui_Subscriber_TextArea, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Subscriber_TextArea, lv_color_hex(0x5F5F62), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Subscriber_TextArea, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Subscriber_TextArea, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Subscriber_TextArea, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Subscriber_TextArea, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_Subscriber_TextArea, LV_BORDER_SIDE_FULL, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_Subscriber_TextArea, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_Subscriber_TextArea, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_Subscriber_TextArea, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_Subscriber_TextArea, 10, LV_PART_MAIN| LV_STATE_DEFAULT);


lv_obj_set_style_text_color(ui_Subscriber_TextArea, lv_color_hex(0x0DF3A7), LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Subscriber_TextArea, 255, LV_PART_TEXTAREA_PLACEHOLDER| LV_STATE_DEFAULT);

ui_Pubscriber_TextArea = lv_textarea_create(ui_mesg_list_panel);
lv_obj_set_width( ui_Pubscriber_TextArea, 101);
lv_obj_set_height( ui_Pubscriber_TextArea, LV_SIZE_CONTENT);   /// 39
lv_obj_set_x( ui_Pubscriber_TextArea, 0 );
lv_obj_set_y( ui_Pubscriber_TextArea, 106 );
lv_obj_set_align( ui_Pubscriber_TextArea, LV_ALIGN_CENTER );
lv_textarea_set_placeholder_text(ui_Pubscriber_TextArea,"Publisher");
lv_textarea_set_one_line(ui_Pubscriber_TextArea,true);
lv_obj_clear_flag( ui_Pubscriber_TextArea, LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_text_color(ui_Pubscriber_TextArea, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Pubscriber_TextArea, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_Pubscriber_TextArea, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Pubscriber_TextArea, &lv_font_montserrat_12, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_radius(ui_Pubscriber_TextArea, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Pubscriber_TextArea, lv_color_hex(0x5F5F62), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Pubscriber_TextArea, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Pubscriber_TextArea, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Pubscriber_TextArea, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Pubscriber_TextArea, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_Pubscriber_TextArea, LV_BORDER_SIDE_FULL, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_Pubscriber_TextArea, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_Pubscriber_TextArea, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_Pubscriber_TextArea, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_Pubscriber_TextArea, 10, LV_PART_MAIN| LV_STATE_DEFAULT);


lv_obj_set_style_text_color(ui_Pubscriber_TextArea, lv_color_hex(0x0DF3A7), LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Pubscriber_TextArea, 255, LV_PART_TEXTAREA_PLACEHOLDER| LV_STATE_DEFAULT);

ui_mesg_handler = lv_label_create(ui_Main_Screen);
lv_obj_set_width( ui_mesg_handler, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_mesg_handler, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_mesg_handler, 67 );
lv_obj_set_y( ui_mesg_handler, -92 );
lv_obj_set_align( ui_mesg_handler, LV_ALIGN_CENTER );
lv_label_set_text(ui_mesg_handler,"|<<   MonitorX console   >>|");
lv_obj_add_flag( ui_mesg_handler, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_FLEX_IN_NEW_TRACK | LV_OBJ_FLAG_EVENT_BUBBLE );   /// Flags
lv_obj_clear_flag( ui_mesg_handler, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_scroll_dir(ui_mesg_handler, LV_DIR_LEFT);
lv_obj_set_style_text_color(ui_mesg_handler, lv_color_hex(0xFDFCFC), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_mesg_handler, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_mesg_handler, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_mesg_handler, &lv_font_montserrat_12, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Console_Textarea = lv_textarea_create(ui_Main_Screen);
lv_obj_set_width( ui_Console_Textarea, 370);
lv_obj_set_height( ui_Console_Textarea, 169);
lv_obj_set_x( ui_Console_Textarea, 55 );
lv_obj_set_y( ui_Console_Textarea, 8 );
lv_obj_set_align( ui_Console_Textarea, LV_ALIGN_CENTER );
lv_textarea_set_text(ui_Console_Textarea,"No Message");
lv_textarea_set_placeholder_text(ui_Console_Textarea,"No Message");
lv_obj_add_flag( ui_Console_Textarea, LV_OBJ_FLAG_HIDDEN );   /// Flags
lv_obj_set_style_text_color(ui_Console_Textarea, lv_color_hex(0xFCFCFC), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Console_Textarea, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_Console_Textarea, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Console_Textarea, &lv_font_montserrat_12, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_radius(ui_Console_Textarea, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Console_Textarea, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Console_Textarea, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Console_Textarea, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Console_Textarea, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Console_Textarea, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_Console_Textarea, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_Console_Textarea, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_Console_Textarea, 20, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_Console_Textarea, 3, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_row(ui_Console_Textarea, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_Console_Textarea, 0, LV_PART_MAIN| LV_STATE_DEFAULT);



ui_SubFunct_panel = lv_obj_create(ui_Main_Screen);
lv_obj_set_width( ui_SubFunct_panel, 224);
lv_obj_set_height( ui_SubFunct_panel, 126);
lv_obj_set_x( ui_SubFunct_panel, 18 );
lv_obj_set_y( ui_SubFunct_panel, -44 );
lv_obj_set_align( ui_SubFunct_panel, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_SubFunct_panel, LV_OBJ_FLAG_HIDDEN );   /// Flags
lv_obj_clear_flag( ui_SubFunct_panel, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_SubFunct_panel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_SubFunct_panel, lv_color_hex(0x5F5F62), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_SubFunct_panel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_SubFunct_panel, lv_color_hex(0x08F485), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_SubFunct_panel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_SubFunct_panel, 2, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_SubTopicHander_Label = lv_label_create(ui_SubFunct_panel);
lv_obj_set_width( ui_SubTopicHander_Label, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_SubTopicHander_Label, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_SubTopicHander_Label, -2 );
lv_obj_set_y( ui_SubTopicHander_Label, -53 );
lv_obj_set_align( ui_SubTopicHander_Label, LV_ALIGN_CENTER );
lv_label_set_text(ui_SubTopicHander_Label,"Subscribe a Topic");
lv_obj_set_style_text_color(ui_SubTopicHander_Label, lv_color_hex(0xFBF7F7), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_SubTopicHander_Label, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_SubTopicHander_Label, &lv_font_montserrat_12, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_SubFuncConfirm_Button = lv_btn_create(ui_SubFunct_panel);
lv_obj_set_width( ui_SubFuncConfirm_Button, 220);
lv_obj_set_height( ui_SubFuncConfirm_Button, 23);
lv_obj_set_x( ui_SubFuncConfirm_Button, 0 );
lv_obj_set_y( ui_SubFuncConfirm_Button, 49 );
lv_obj_set_align( ui_SubFuncConfirm_Button, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_SubFuncConfirm_Button, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_SubFuncConfirm_Button, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_SubFuncConfirm_Button, 8, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_SubFuncConfirm_Button, lv_color_hex(0x5F5F62), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_SubFuncConfirm_Button, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_SubFuncConfirm_Button, lv_color_hex(0x403B3B), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_SubFuncConfirm_Button, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_SubFuncConfirm_Button, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_SubFuncConfirm_Button, LV_BORDER_SIDE_FULL, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_SubFuncWord_label = lv_label_create(ui_SubFunct_panel);
lv_obj_set_width( ui_SubFuncWord_label, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_SubFuncWord_label, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_SubFuncWord_label, -2 );
lv_obj_set_y( ui_SubFuncWord_label, 49 );
lv_obj_set_align( ui_SubFuncWord_label, LV_ALIGN_CENTER );
lv_label_set_text(ui_SubFuncWord_label,"Subscribe");
lv_obj_set_style_text_color(ui_SubFuncWord_label, lv_color_hex(0x15F8FA), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_SubFuncWord_label, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_SubFuncWord_label, &lv_font_montserrat_12, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_CloseFigure1 = lv_img_create(ui_SubFunct_panel);
lv_img_set_src(ui_CloseFigure1, &ui_img_close_png);
lv_obj_set_width( ui_CloseFigure1, LV_SIZE_CONTENT);  /// 16
lv_obj_set_height( ui_CloseFigure1, LV_SIZE_CONTENT);   /// 16
lv_obj_set_x( ui_CloseFigure1, 102 );
lv_obj_set_y( ui_CloseFigure1, -53 );
lv_obj_set_align( ui_CloseFigure1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_CloseFigure1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_CloseFigure1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_SubFuncConsole_panel = lv_obj_create(ui_SubFunct_panel);
lv_obj_set_width( ui_SubFuncConsole_panel, 220);
lv_obj_set_height( ui_SubFuncConsole_panel, 81);
lv_obj_set_x( ui_SubFuncConsole_panel, 0 );
lv_obj_set_y( ui_SubFuncConsole_panel, -3 );
lv_obj_set_align( ui_SubFuncConsole_panel, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_SubFuncConsole_panel, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_SubFuncConsole_panel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_SubFuncConsole_panel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_SubFuncConsole_panel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_SubFuncConsole_panel, lv_color_hex(0x154258), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_SubFuncConsole_panel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_SubFuncConsole_panel, 1, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_SubNodeName_label = lv_label_create(ui_SubFuncConsole_panel);
lv_obj_set_width( ui_SubNodeName_label, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_SubNodeName_label, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_SubNodeName_label, -72 );
lv_obj_set_y( ui_SubNodeName_label, -26 );
lv_obj_set_align( ui_SubNodeName_label, LV_ALIGN_CENTER );
lv_label_set_text(ui_SubNodeName_label,"Node Name:");
lv_obj_set_style_text_color(ui_SubNodeName_label, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_SubNodeName_label, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_SubNodeName_label, &lv_font_montserrat_10, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_SubMsgType_label = lv_label_create(ui_SubFuncConsole_panel);
lv_obj_set_width( ui_SubMsgType_label, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_SubMsgType_label, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_SubMsgType_label, -72 );
lv_obj_set_y( ui_SubMsgType_label, -1 );
lv_obj_set_align( ui_SubMsgType_label, LV_ALIGN_CENTER );
lv_label_set_text(ui_SubMsgType_label,"Msg Type:");
lv_obj_set_style_text_color(ui_SubMsgType_label, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_SubMsgType_label, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_SubMsgType_label, &lv_font_montserrat_10, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_TopicName_label = lv_label_create(ui_SubFuncConsole_panel);
lv_obj_set_width( ui_TopicName_label, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_TopicName_label, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_TopicName_label, -71 );
lv_obj_set_y( ui_TopicName_label, 27 );
lv_obj_set_align( ui_TopicName_label, LV_ALIGN_CENTER );
lv_label_set_text(ui_TopicName_label,"Topic Name:");
lv_obj_set_style_text_color(ui_TopicName_label, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_TopicName_label, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_TopicName_label, &lv_font_montserrat_10, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_SubNodeName_textarea = lv_textarea_create(ui_SubFuncConsole_panel);
lv_obj_set_width( ui_SubNodeName_textarea, 137);
lv_obj_set_height( ui_SubNodeName_textarea, LV_SIZE_CONTENT);   /// 39
lv_obj_set_x( ui_SubNodeName_textarea, 36 );
lv_obj_set_y( ui_SubNodeName_textarea, -24 );
lv_obj_set_align( ui_SubNodeName_textarea, LV_ALIGN_CENTER );
lv_textarea_set_placeholder_text(ui_SubNodeName_textarea,"...");
lv_textarea_set_one_line(ui_SubNodeName_textarea,true);
lv_obj_set_style_text_color(ui_SubNodeName_textarea, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_SubNodeName_textarea, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_SubNodeName_textarea, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_SubNodeName_textarea, &lv_font_montserrat_10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_radius(ui_SubNodeName_textarea, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_SubNodeName_textarea, lv_color_hex(0x5F5F62), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_SubNodeName_textarea, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_SubNodeName_textarea, lv_color_hex(0x1AB985), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_SubNodeName_textarea, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_SubNodeName_textarea, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_SubNodeName_textarea, LV_BORDER_SIDE_FULL, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_SubNodeName_textarea, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_SubNodeName_textarea, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_SubNodeName_textarea, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_SubNodeName_textarea, 5, LV_PART_MAIN| LV_STATE_DEFAULT);



ui_SubMsgType_textarea = lv_textarea_create(ui_SubFuncConsole_panel);
lv_obj_set_width( ui_SubMsgType_textarea, 137);
lv_obj_set_height( ui_SubMsgType_textarea, LV_SIZE_CONTENT);   /// 39
lv_obj_set_x( ui_SubMsgType_textarea, 36 );
lv_obj_set_y( ui_SubMsgType_textarea, 1 );
lv_obj_set_align( ui_SubMsgType_textarea, LV_ALIGN_CENTER );
lv_textarea_set_placeholder_text(ui_SubMsgType_textarea,"...");
lv_textarea_set_one_line(ui_SubMsgType_textarea,true);
lv_obj_set_style_text_color(ui_SubMsgType_textarea, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_SubMsgType_textarea, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_SubMsgType_textarea, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_SubMsgType_textarea, &lv_font_montserrat_10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_radius(ui_SubMsgType_textarea, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_SubMsgType_textarea, lv_color_hex(0x5F5F62), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_SubMsgType_textarea, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_SubMsgType_textarea, lv_color_hex(0x1AB985), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_SubMsgType_textarea, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_SubMsgType_textarea, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_SubMsgType_textarea, LV_BORDER_SIDE_FULL, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_SubMsgType_textarea, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_SubMsgType_textarea, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_SubMsgType_textarea, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_SubMsgType_textarea, 5, LV_PART_MAIN| LV_STATE_DEFAULT);



ui_SubTopicNameMsg_textarea = lv_textarea_create(ui_SubFuncConsole_panel);
lv_obj_set_width( ui_SubTopicNameMsg_textarea, 137);
lv_obj_set_height( ui_SubTopicNameMsg_textarea, LV_SIZE_CONTENT);   /// 39
lv_obj_set_x( ui_SubTopicNameMsg_textarea, 36 );
lv_obj_set_y( ui_SubTopicNameMsg_textarea, 26 );
lv_obj_set_align( ui_SubTopicNameMsg_textarea, LV_ALIGN_CENTER );
lv_textarea_set_placeholder_text(ui_SubTopicNameMsg_textarea,"...");
lv_textarea_set_one_line(ui_SubTopicNameMsg_textarea,true);
lv_obj_set_style_text_color(ui_SubTopicNameMsg_textarea, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_SubTopicNameMsg_textarea, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_SubTopicNameMsg_textarea, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_SubTopicNameMsg_textarea, &lv_font_montserrat_10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_radius(ui_SubTopicNameMsg_textarea, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_SubTopicNameMsg_textarea, lv_color_hex(0x5F5F62), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_SubTopicNameMsg_textarea, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_SubTopicNameMsg_textarea, lv_color_hex(0x1AB985), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_SubTopicNameMsg_textarea, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_SubTopicNameMsg_textarea, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_SubTopicNameMsg_textarea, LV_BORDER_SIDE_FULL, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_SubTopicNameMsg_textarea, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_SubTopicNameMsg_textarea, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_SubTopicNameMsg_textarea, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_SubTopicNameMsg_textarea, 5, LV_PART_MAIN| LV_STATE_DEFAULT);



ui_PubFunct_panel = lv_obj_create(ui_Main_Screen);
lv_obj_set_width( ui_PubFunct_panel, 224);
lv_obj_set_height( ui_PubFunct_panel, 126);
lv_obj_set_x( ui_PubFunct_panel, 18 );
lv_obj_set_y( ui_PubFunct_panel, -44 );
lv_obj_set_align( ui_PubFunct_panel, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_PubFunct_panel, LV_OBJ_FLAG_HIDDEN );   /// Flags
lv_obj_clear_flag( ui_PubFunct_panel, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_PubFunct_panel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_PubFunct_panel, lv_color_hex(0x5F5F62), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_PubFunct_panel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_PubFunct_panel, lv_color_hex(0x08F485), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_PubFunct_panel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_PubFunct_panel, 2, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_PubTopicHander_Label = lv_label_create(ui_PubFunct_panel);
lv_obj_set_width( ui_PubTopicHander_Label, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_PubTopicHander_Label, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_PubTopicHander_Label, -1 );
lv_obj_set_y( ui_PubTopicHander_Label, -53 );
lv_obj_set_align( ui_PubTopicHander_Label, LV_ALIGN_CENTER );
lv_label_set_text(ui_PubTopicHander_Label,"Publish a Topic");
lv_obj_set_style_text_color(ui_PubTopicHander_Label, lv_color_hex(0xFBF7F7), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_PubTopicHander_Label, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_PubTopicHander_Label, &lv_font_montserrat_12, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_PubFuncConfirm_Button = lv_btn_create(ui_PubFunct_panel);
lv_obj_set_width( ui_PubFuncConfirm_Button, 220);
lv_obj_set_height( ui_PubFuncConfirm_Button, 23);
lv_obj_set_x( ui_PubFuncConfirm_Button, 0 );
lv_obj_set_y( ui_PubFuncConfirm_Button, 51 );
lv_obj_set_align( ui_PubFuncConfirm_Button, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_PubFuncConfirm_Button, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_PubFuncConfirm_Button, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_PubFuncConfirm_Button, 8, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_PubFuncConfirm_Button, lv_color_hex(0x5F5F62), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_PubFuncConfirm_Button, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_PubFuncConfirm_Button, lv_color_hex(0x403B3B), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_PubFuncConfirm_Button, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_PubFuncConfirm_Button, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_PubFuncConfirm_Button, LV_BORDER_SIDE_FULL, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_PubFuncWord_label = lv_label_create(ui_PubFunct_panel);
lv_obj_set_width( ui_PubFuncWord_label, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_PubFuncWord_label, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_PubFuncWord_label, -2 );
lv_obj_set_y( ui_PubFuncWord_label, 50 );
lv_obj_set_align( ui_PubFuncWord_label, LV_ALIGN_CENTER );
lv_label_set_text(ui_PubFuncWord_label,"Publish");
lv_obj_set_style_text_color(ui_PubFuncWord_label, lv_color_hex(0x15F8FA), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_PubFuncWord_label, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_PubFuncWord_label, &lv_font_montserrat_12, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_CloseFigure2 = lv_img_create(ui_PubFunct_panel);
lv_img_set_src(ui_CloseFigure2, &ui_img_close_png);
lv_obj_set_width( ui_CloseFigure2, LV_SIZE_CONTENT);  /// 16
lv_obj_set_height( ui_CloseFigure2, LV_SIZE_CONTENT);   /// 16
lv_obj_set_x( ui_CloseFigure2, 103 );
lv_obj_set_y( ui_CloseFigure2, -53 );
lv_obj_set_align( ui_CloseFigure2, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_CloseFigure2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_CloseFigure2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_PubFuncConsole_panel = lv_obj_create(ui_PubFunct_panel);
lv_obj_set_width( ui_PubFuncConsole_panel, 220);
lv_obj_set_height( ui_PubFuncConsole_panel, 84);
lv_obj_set_x( ui_PubFuncConsole_panel, 1 );
lv_obj_set_y( ui_PubFuncConsole_panel, -1 );
lv_obj_set_align( ui_PubFuncConsole_panel, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_PubFuncConsole_panel, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_PubFuncConsole_panel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_PubFuncConsole_panel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_PubFuncConsole_panel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_PubFuncConsole_panel, lv_color_hex(0x154258), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_PubFuncConsole_panel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_PubFuncConsole_panel, 1, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_PubNodeName_label = lv_label_create(ui_PubFuncConsole_panel);
lv_obj_set_width( ui_PubNodeName_label, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_PubNodeName_label, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_PubNodeName_label, -73 );
lv_obj_set_y( ui_PubNodeName_label, -25 );
lv_obj_set_align( ui_PubNodeName_label, LV_ALIGN_CENTER );
lv_label_set_text(ui_PubNodeName_label,"Node Name:");
lv_obj_set_style_text_color(ui_PubNodeName_label, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_PubNodeName_label, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_PubNodeName_label, &lv_font_montserrat_10, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_PubNodeID_label = lv_label_create(ui_PubFuncConsole_panel);
lv_obj_set_width( ui_PubNodeID_label, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_PubNodeID_label, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_PubNodeID_label, -73 );
lv_obj_set_y( ui_PubNodeID_label, 0 );
lv_obj_set_align( ui_PubNodeID_label, LV_ALIGN_CENTER );
lv_label_set_text(ui_PubNodeID_label,"Node id:");
lv_obj_set_style_text_color(ui_PubNodeID_label, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_PubNodeID_label, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_PubNodeID_label, &lv_font_montserrat_10, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_PubTopicName_label = lv_label_create(ui_PubFuncConsole_panel);
lv_obj_set_width( ui_PubTopicName_label, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_PubTopicName_label, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_PubTopicName_label, -71 );
lv_obj_set_y( ui_PubTopicName_label, 26 );
lv_obj_set_align( ui_PubTopicName_label, LV_ALIGN_CENTER );
lv_label_set_text(ui_PubTopicName_label,"Topic Name:");
lv_obj_set_style_text_color(ui_PubTopicName_label, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_PubTopicName_label, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_PubTopicName_label, &lv_font_montserrat_10, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_PubNodeName_textarea = lv_textarea_create(ui_PubFuncConsole_panel);
lv_obj_set_width( ui_PubNodeName_textarea, 137);
lv_obj_set_height( ui_PubNodeName_textarea, LV_SIZE_CONTENT);   /// 39
lv_obj_set_x( ui_PubNodeName_textarea, 35 );
lv_obj_set_y( ui_PubNodeName_textarea, -26 );
lv_obj_set_align( ui_PubNodeName_textarea, LV_ALIGN_CENTER );
lv_textarea_set_placeholder_text(ui_PubNodeName_textarea,"...");
lv_textarea_set_one_line(ui_PubNodeName_textarea,true);
lv_obj_set_style_text_color(ui_PubNodeName_textarea, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_PubNodeName_textarea, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_PubNodeName_textarea, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_PubNodeName_textarea, &lv_font_montserrat_10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_radius(ui_PubNodeName_textarea, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_PubNodeName_textarea, lv_color_hex(0x5F5F62), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_PubNodeName_textarea, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_PubNodeName_textarea, lv_color_hex(0x1AB985), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_PubNodeName_textarea, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_PubNodeName_textarea, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_PubNodeName_textarea, LV_BORDER_SIDE_FULL, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_PubNodeName_textarea, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_PubNodeName_textarea, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_PubNodeName_textarea, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_PubNodeName_textarea, 5, LV_PART_MAIN| LV_STATE_DEFAULT);



ui_PubNodeID_textarea = lv_textarea_create(ui_PubFuncConsole_panel);
lv_obj_set_width( ui_PubNodeID_textarea, 137);
lv_obj_set_height( ui_PubNodeID_textarea, LV_SIZE_CONTENT);   /// 39
lv_obj_set_x( ui_PubNodeID_textarea, 35 );
lv_obj_set_y( ui_PubNodeID_textarea, 0 );
lv_obj_set_align( ui_PubNodeID_textarea, LV_ALIGN_CENTER );
lv_textarea_set_placeholder_text(ui_PubNodeID_textarea,"...");
lv_textarea_set_one_line(ui_PubNodeID_textarea,true);
lv_obj_set_style_text_color(ui_PubNodeID_textarea, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_PubNodeID_textarea, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_PubNodeID_textarea, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_PubNodeID_textarea, &lv_font_montserrat_10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_radius(ui_PubNodeID_textarea, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_PubNodeID_textarea, lv_color_hex(0x5F5F62), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_PubNodeID_textarea, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_PubNodeID_textarea, lv_color_hex(0x1AB985), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_PubNodeID_textarea, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_PubNodeID_textarea, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_PubNodeID_textarea, LV_BORDER_SIDE_FULL, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_PubNodeID_textarea, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_PubNodeID_textarea, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_PubNodeID_textarea, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_PubNodeID_textarea, 5, LV_PART_MAIN| LV_STATE_DEFAULT);



ui_PubTopicNameMsg_textarea = lv_textarea_create(ui_PubFuncConsole_panel);
lv_obj_set_width( ui_PubTopicNameMsg_textarea, 137);
lv_obj_set_height( ui_PubTopicNameMsg_textarea, LV_SIZE_CONTENT);   /// 39
lv_obj_set_x( ui_PubTopicNameMsg_textarea, 35 );
lv_obj_set_y( ui_PubTopicNameMsg_textarea, 26 );
lv_obj_set_align( ui_PubTopicNameMsg_textarea, LV_ALIGN_CENTER );
lv_textarea_set_placeholder_text(ui_PubTopicNameMsg_textarea,"...");
lv_textarea_set_one_line(ui_PubTopicNameMsg_textarea,true);
lv_obj_set_style_text_color(ui_PubTopicNameMsg_textarea, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_PubTopicNameMsg_textarea, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_PubTopicNameMsg_textarea, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_PubTopicNameMsg_textarea, &lv_font_montserrat_10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_radius(ui_PubTopicNameMsg_textarea, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_PubTopicNameMsg_textarea, lv_color_hex(0x5F5F62), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_PubTopicNameMsg_textarea, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_PubTopicNameMsg_textarea, lv_color_hex(0x1AB985), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_PubTopicNameMsg_textarea, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_PubTopicNameMsg_textarea, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_PubTopicNameMsg_textarea, LV_BORDER_SIDE_FULL, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_PubTopicNameMsg_textarea, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_PubTopicNameMsg_textarea, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_PubTopicNameMsg_textarea, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_PubTopicNameMsg_textarea, 5, LV_PART_MAIN| LV_STATE_DEFAULT);



ui_Func_Ctrl_Panel = lv_obj_create(ui_Main_Screen);
lv_obj_set_width( ui_Func_Ctrl_Panel, 160);
lv_obj_set_height( ui_Func_Ctrl_Panel, 39);
lv_obj_set_x( ui_Func_Ctrl_Panel, -162 );
lv_obj_set_y( ui_Func_Ctrl_Panel, 114 );
lv_obj_set_align( ui_Func_Ctrl_Panel, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Func_Ctrl_Panel, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_Func_Ctrl_Panel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Func_Ctrl_Panel, lv_color_hex(0x7C7474), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Func_Ctrl_Panel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Func_Ctrl_Panel, lv_color_hex(0x7C7474), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Func_Ctrl_Panel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Func_Ctrl_Panel, 3, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_Func_Ctrl_Panel, LV_BORDER_SIDE_FULL, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_blend_mode(ui_Func_Ctrl_Panel, LV_BLEND_MODE_MULTIPLY, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_opa(ui_Func_Ctrl_Panel, 50, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Func_Ctrl_label = lv_label_create(ui_Main_Screen);
lv_obj_set_width( ui_Func_Ctrl_label, LV_SIZE_CONTENT);  /// -673
lv_obj_set_height( ui_Func_Ctrl_label, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Func_Ctrl_label, -169 );
lv_obj_set_y( ui_Func_Ctrl_label, 116 );
lv_obj_set_align( ui_Func_Ctrl_label, LV_ALIGN_CENTER );
lv_label_set_text(ui_Func_Ctrl_label,"Func Ctrl");
lv_obj_add_flag( ui_Func_Ctrl_label, LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_set_style_text_color(ui_Func_Ctrl_label, lv_color_hex(0x0DF3A7), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Func_Ctrl_label, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Turtlesim_Demo_Panel = lv_obj_create(ui_Main_Screen);
lv_obj_set_width( ui_Turtlesim_Demo_Panel, 160);
lv_obj_set_height( ui_Turtlesim_Demo_Panel, 39);
lv_obj_set_x( ui_Turtlesim_Demo_Panel, -1 );
lv_obj_set_y( ui_Turtlesim_Demo_Panel, 114 );
lv_obj_set_align( ui_Turtlesim_Demo_Panel, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Turtlesim_Demo_Panel, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_Turtlesim_Demo_Panel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Turtlesim_Demo_Panel, lv_color_hex(0x7C7474), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Turtlesim_Demo_Panel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Turtlesim_Demo_Panel, lv_color_hex(0x504646), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Turtlesim_Demo_Panel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Turtlesim_Demo_Panel, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_blend_mode(ui_Turtlesim_Demo_Panel, LV_BLEND_MODE_MULTIPLY, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_opa(ui_Turtlesim_Demo_Panel, 50, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Turtlesim_Demo_Label = lv_label_create(ui_Main_Screen);
lv_obj_set_width( ui_Turtlesim_Demo_Label, LV_SIZE_CONTENT);  /// -7
lv_obj_set_height( ui_Turtlesim_Demo_Label, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Turtlesim_Demo_Label, 2 );
lv_obj_set_y( ui_Turtlesim_Demo_Label, 116 );
lv_obj_set_align( ui_Turtlesim_Demo_Label, LV_ALIGN_CENTER );
lv_label_set_text(ui_Turtlesim_Demo_Label,"Turtlesim Demo");
lv_obj_add_flag( ui_Turtlesim_Demo_Label, LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_set_style_text_color(ui_Turtlesim_Demo_Label, lv_color_hex(0x0DF3A7), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Turtlesim_Demo_Label, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Turtlesim_background = lv_img_create(ui_Main_Screen);
lv_img_set_src(ui_Turtlesim_background, &ui_img_tortle_background_png);
lv_obj_set_width( ui_Turtlesim_background, LV_SIZE_CONTENT);  /// 375
lv_obj_set_height( ui_Turtlesim_background, LV_SIZE_CONTENT);   /// 198
lv_obj_set_x( ui_Turtlesim_background, 52 );
lv_obj_set_y( ui_Turtlesim_background, -6 );
lv_obj_set_align( ui_Turtlesim_background, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Turtlesim_background, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Turtlesim_background, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Terminal_TextArea = lv_textarea_create(ui_Main_Screen);
lv_obj_set_width( ui_Terminal_TextArea, 102);
lv_obj_set_height( ui_Terminal_TextArea, 176);
lv_obj_set_x( ui_Terminal_TextArea, -188 );
lv_obj_set_y( ui_Terminal_TextArea, 5 );
lv_obj_set_align( ui_Terminal_TextArea, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Terminal_TextArea, LV_OBJ_FLAG_HIDDEN );   /// Flags
lv_obj_set_style_text_color(ui_Terminal_TextArea, lv_color_hex(0xFDFAFA), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Terminal_TextArea, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Terminal_TextArea, &lv_font_montserrat_12, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_radius(ui_Terminal_TextArea, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Terminal_TextArea, lv_color_hex(0x3A1342), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Terminal_TextArea, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Terminal_TextArea, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Terminal_TextArea, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Terminal_TextArea, 1, LV_PART_MAIN| LV_STATE_DEFAULT);


lv_obj_set_style_text_color(ui_Terminal_TextArea, lv_color_hex(0xFFFEFE), LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Terminal_TextArea, 255, LV_PART_TEXTAREA_PLACEHOLDER| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_Terminal_TextArea, LV_TEXT_ALIGN_AUTO, LV_PART_TEXTAREA_PLACEHOLDER| LV_STATE_DEFAULT);

ui_Turtle_Figure = lv_img_create(ui_Main_Screen);
lv_img_set_src(ui_Turtle_Figure, &ui_img_turtle_png);
lv_obj_set_width( ui_Turtle_Figure, LV_SIZE_CONTENT);  /// 16
lv_obj_set_height( ui_Turtle_Figure, LV_SIZE_CONTENT);   /// 16
lv_obj_set_x( ui_Turtle_Figure, 53 );
lv_obj_set_y( ui_Turtle_Figure, 5 );
lv_obj_set_align( ui_Turtle_Figure, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Turtle_Figure, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Turtle_Figure, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Terminal_Figure = lv_img_create(ui_Main_Screen);
lv_img_set_src(ui_Terminal_Figure, &ui_img_terminal_png);
lv_obj_set_width( ui_Terminal_Figure, LV_SIZE_CONTENT);  /// 102
lv_obj_set_height( ui_Terminal_Figure, LV_SIZE_CONTENT);   /// 22
lv_obj_set_x( ui_Terminal_Figure, -188 );
lv_obj_set_y( ui_Terminal_Figure, -94 );
lv_obj_set_align( ui_Terminal_Figure, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Terminal_Figure, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Terminal_Figure, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Information_panel = lv_obj_create(ui_Main_Screen);
lv_obj_set_width( ui_Information_panel, 160);
lv_obj_set_height( ui_Information_panel, 39);
lv_obj_set_x( ui_Information_panel, 160 );
lv_obj_set_y( ui_Information_panel, 114 );
lv_obj_set_align( ui_Information_panel, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Information_panel, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_Information_panel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Information_panel, lv_color_hex(0x7C7474), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Information_panel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Information_panel, lv_color_hex(0x504646), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Information_panel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Information_panel, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_blend_mode(ui_Information_panel, LV_BLEND_MODE_MULTIPLY, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_opa(ui_Information_panel, 50, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Information_label = lv_label_create(ui_Main_Screen);
lv_obj_set_width( ui_Information_label, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Information_label, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Information_label, 161 );
lv_obj_set_y( ui_Information_label, 115 );
lv_obj_set_align( ui_Information_label, LV_ALIGN_CENTER );
lv_label_set_text(ui_Information_label,"Information");
lv_obj_add_flag( ui_Information_label, LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_set_style_text_color(ui_Information_label, lv_color_hex(0x0DF3A7), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Information_label, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Keyboard = lv_keyboard_create(ui_Main_Screen);
lv_obj_set_width( ui_Keyboard, 475);
lv_obj_set_height( ui_Keyboard, 116);
lv_obj_set_x( ui_Keyboard, 0 );
lv_obj_set_y( ui_Keyboard, 75 );
lv_obj_set_align( ui_Keyboard, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Keyboard, LV_OBJ_FLAG_HIDDEN );   /// Flags
lv_obj_set_style_radius(ui_Keyboard, 20, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Keyboard, lv_color_hex(0xB1ADAD), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Keyboard, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_dir(ui_Keyboard, LV_GRAD_DIR_VER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Keyboard, lv_color_hex(0x847373), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Keyboard, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Keyboard, 2, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Calendar = lv_calendar_create(ui_Main_Screen);
lv_calendar_set_today_date(ui_Calendar,2024,4,19);
lv_calendar_set_showed_date(ui_Calendar,2024,4);
lv_obj_t *ui_Calendar_header = lv_calendar_header_arrow_create(ui_Calendar);
lv_obj_set_width( ui_Calendar, 178);
lv_obj_set_height( ui_Calendar, 178);
lv_obj_set_x( ui_Calendar, 152 );
lv_obj_set_y( ui_Calendar, -16 );
lv_obj_set_align( ui_Calendar, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Calendar, LV_OBJ_FLAG_HIDDEN );   /// Flags

ui_console_desc1 = lv_textarea_create(ui_Main_Screen);
lv_obj_set_width( ui_console_desc1, 425);
lv_obj_set_height( ui_console_desc1, LV_SIZE_CONTENT);   /// 109
lv_obj_set_x( ui_console_desc1, 0 );
lv_obj_set_y( ui_console_desc1, -46 );
lv_obj_set_align( ui_console_desc1, LV_ALIGN_CENTER );
lv_textarea_set_text(ui_console_desc1,"- micro-ROS terminal console based on RT-Thread\n- Support for manual configuration of transport modes (UART, TCP, UDP, Ethernet)\n- Support Topic subscription and details\n- Support currently available Node and Topic display\n- ...");
lv_obj_add_flag( ui_console_desc1, LV_OBJ_FLAG_HIDDEN );   /// Flags
lv_obj_clear_flag( ui_console_desc1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_scrollbar_mode(ui_console_desc1, LV_SCROLLBAR_MODE_ACTIVE);
lv_obj_set_style_text_color(ui_console_desc1, lv_color_hex(0x8B2D2D), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_console_desc1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_console_desc1, lv_color_hex(0x4BE2B0), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_console_desc1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);



lv_obj_add_event_cb(ui_console2_desc, ui_event_console2_desc, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_return_button, ui_event_return_button, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_calendar_label, ui_event_calendar_label, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_List_Topic_Dropdown, ui_event_List_Topic_Dropdown, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_List_Node_Dropdown, ui_event_List_Node_Dropdown, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Search_Topic_TextArea, ui_event_Search_Topic_TextArea, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Search_Node_TextArea, ui_event_Search_Node_TextArea, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Subscriber_TextArea, ui_event_Subscriber_TextArea, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Pubscriber_TextArea, ui_event_Pubscriber_TextArea, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_SubFuncConfirm_Button, ui_event_SubFuncConfirm_Button, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_CloseFigure1, ui_event_CloseFigure1, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_SubNodeName_textarea, ui_event_SubNodeName_textarea, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_SubMsgType_textarea, ui_event_SubMsgType_textarea, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_SubTopicNameMsg_textarea, ui_event_SubTopicNameMsg_textarea, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_PubFuncConfirm_Button, ui_event_PubFuncConfirm_Button, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_CloseFigure2, ui_event_CloseFigure2, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_PubNodeName_textarea, ui_event_PubNodeName_textarea, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_PubNodeID_textarea, ui_event_PubNodeID_textarea, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_PubTopicNameMsg_textarea, ui_event_PubTopicNameMsg_textarea, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Func_Ctrl_label, ui_event_Func_Ctrl_label, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Turtlesim_Demo_Label, ui_event_Turtlesim_Demo_Label, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Information_label, ui_event_Information_label, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Keyboard, ui_event_Keyboard, LV_EVENT_ALL, NULL);

}
