// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_start_menu_screen_init(void)
{
ui_start_menu = lv_obj_create(NULL);
lv_obj_clear_flag( ui_start_menu, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_start_menu, lv_color_hex(0x5F5F62), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_start_menu, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_rtt_logo = lv_img_create(ui_start_menu);
lv_img_set_src(ui_rtt_logo, &ui_img_microros_rtt_png);
lv_obj_set_width( ui_rtt_logo, LV_SIZE_CONTENT);  /// 480
lv_obj_set_height( ui_rtt_logo, LV_SIZE_CONTENT);   /// 116
lv_obj_set_x( ui_rtt_logo, -3 );
lv_obj_set_y( ui_rtt_logo, 2 );
lv_obj_set_align( ui_rtt_logo, LV_ALIGN_TOP_MID );
lv_obj_add_flag( ui_rtt_logo, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_rtt_logo, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_console_name = lv_label_create(ui_start_menu);
lv_obj_set_width( ui_console_name, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_console_name, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_console_name, -2 );
lv_obj_set_y( ui_console_name, -6 );
lv_obj_set_align( ui_console_name, LV_ALIGN_CENTER );
lv_label_set_text(ui_console_name,"RT-MROS MonitorX");
lv_obj_add_flag( ui_console_name, LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_clear_flag( ui_console_name, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_text_color(ui_console_name, lv_color_hex(0x0CA4A0), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_console_name, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_console_name, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_decor(ui_console_name, LV_TEXT_DECOR_UNDERLINE, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_console_name, &lv_font_montserrat_28, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_gui_describer = lv_label_create(ui_start_menu);
lv_obj_set_width( ui_gui_describer, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_gui_describer, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_gui_describer, 1 );
lv_obj_set_y( ui_gui_describer, 31 );
lv_obj_set_align( ui_gui_describer, LV_ALIGN_CENTER );
lv_label_set_text(ui_gui_describer,"Micro-ROS & RT-Thread Message terminal");
lv_obj_set_style_text_align(ui_gui_describer, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ImgButton3 = lv_imgbtn_create(ui_start_menu);
lv_imgbtn_set_src(ui_ImgButton3, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_startup_png, NULL);
lv_obj_set_height( ui_ImgButton3, 52);
lv_obj_set_width( ui_ImgButton3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_x( ui_ImgButton3, 11 );
lv_obj_set_y( ui_ImgButton3, 91 );
lv_obj_set_align( ui_ImgButton3, LV_ALIGN_CENTER );

ui_console_desc = lv_textarea_create(ui_start_menu);
lv_obj_set_width( ui_console_desc, 425);
lv_obj_set_height( ui_console_desc, 109);
lv_obj_set_x( ui_console_desc, 1 );
lv_obj_set_y( ui_console_desc, 73 );
lv_obj_set_align( ui_console_desc, LV_ALIGN_CENTER );
lv_textarea_set_text(ui_console_desc,"- micro-ROS terminal console based on RT-Thread\n- Support for manual configuration of transport modes (UART, TCP, UDP, Ethernet)\n- Support Topic subscription and details\n- Support currently available Node and Topic display\n- ...");
lv_obj_add_flag( ui_console_desc, LV_OBJ_FLAG_HIDDEN );   /// Flags
lv_obj_clear_flag( ui_console_desc, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_scrollbar_mode(ui_console_desc, LV_SCROLLBAR_MODE_ACTIVE);
lv_obj_set_style_text_color(ui_console_desc, lv_color_hex(0x8B2D2D), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_console_desc, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_console_desc, lv_color_hex(0x4BE2B0), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_console_desc, 255, LV_PART_MAIN| LV_STATE_DEFAULT);



lv_obj_add_event_cb(ui_console_name, ui_event_console_name, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_ImgButton3, ui_event_ImgButton3, LV_EVENT_ALL, NULL);

}
