// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

    #include "lvgl/lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"
// SCREEN: ui_start_menu
void ui_start_menu_screen_init(void);
extern lv_obj_t *ui_start_menu;
extern lv_obj_t *ui_Image2;
extern lv_obj_t *ui_Label1;
extern lv_obj_t *ui_Label2;
void ui_event_Image3( lv_event_t * e);
extern lv_obj_t *ui_Image3;
// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
void ui_event_Screen2( lv_event_t * e);
extern lv_obj_t *ui_Screen2;
extern lv_obj_t *ui_Label3;
extern lv_obj_t *ui____initial_actions0;

LV_IMG_DECLARE( ui_img_startup_png);   // assets\startup.png
LV_IMG_DECLARE( ui_img_microros_rtt_png);   // assets\microros_rtt.png

LV_FONT_DECLARE( ui_font_Font1en);

void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
