// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_start_menu_screen_init(void)
{
ui_start_menu = lv_obj_create(NULL);
lv_obj_clear_flag( ui_start_menu, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_start_menu, lv_color_hex(0x5F5F62), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_start_menu, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Image2 = lv_img_create(ui_start_menu);
lv_img_set_src(ui_Image2, &ui_img_microros_rtt_png);
lv_obj_set_width( ui_Image2, LV_SIZE_CONTENT);  /// 480
lv_obj_set_height( ui_Image2, LV_SIZE_CONTENT);   /// 116
lv_obj_set_x( ui_Image2, -1 );
lv_obj_set_y( ui_Image2, 3 );
lv_obj_set_align( ui_Image2, LV_ALIGN_TOP_MID );
lv_obj_add_flag( ui_Image2, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label1 = lv_label_create(ui_start_menu);
lv_obj_set_width( ui_Label1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label1, -2 );
lv_obj_set_y( ui_Label1, -6 );
lv_obj_set_align( ui_Label1, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label1,"RT-MROS MonitorX");
lv_obj_set_style_text_color(ui_Label1, lv_color_hex(0x0CA4A0), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_Label1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_decor(ui_Label1, LV_TEXT_DECOR_UNDERLINE, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label1, &lv_font_montserrat_28, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label2 = lv_label_create(ui_start_menu);
lv_obj_set_width( ui_Label2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label2, 1 );
lv_obj_set_y( ui_Label2, 23 );
lv_obj_set_align( ui_Label2, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label2,"Micro-ROS & RT-Thread Message terminal");
lv_obj_set_style_text_align(ui_Label2, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Image3 = lv_img_create(ui_start_menu);
lv_img_set_src(ui_Image3, &ui_img_startup_png);
lv_obj_set_width( ui_Image3, LV_SIZE_CONTENT);  /// 48
lv_obj_set_height( ui_Image3, LV_SIZE_CONTENT);   /// 48
lv_obj_set_x( ui_Image3, -12 );
lv_obj_set_y( ui_Image3, 83 );
lv_obj_set_align( ui_Image3, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

lv_obj_add_event_cb(ui_Image3, ui_event_Image3, LV_EVENT_ALL, NULL);

}
