// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"


// COMPONENT wifi

lv_obj_t *ui_wifi_create(lv_obj_t *comp_parent) {

lv_obj_t *cui_wifi;
cui_wifi = lv_img_create(comp_parent);
lv_obj_set_width( cui_wifi, LV_SIZE_CONTENT);  /// 16
lv_obj_set_height( cui_wifi, LV_SIZE_CONTENT);   /// 16
lv_obj_set_x( cui_wifi, 175 );
lv_obj_set_y( cui_wifi, -122 );
lv_obj_set_align( cui_wifi, LV_ALIGN_CENTER );
lv_obj_add_flag( cui_wifi, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( cui_wifi, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_WIFI_NUM);
children[UI_COMP_WIFI_WIFI] = cui_wifi;
lv_obj_add_event_cb(cui_wifi, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
lv_obj_add_event_cb(cui_wifi, del_component_child_event_cb, LV_EVENT_DELETE, children);
ui_comp_wifi_create_hook(cui_wifi);
return cui_wifi; 
}

