// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"


// COMPONENT Bar1

lv_obj_t *ui_Bar1_create(lv_obj_t *comp_parent) {

lv_obj_t *cui_Bar1;
cui_Bar1 = lv_bar_create(comp_parent);
lv_bar_set_value(cui_Bar1,100,LV_ANIM_OFF);
lv_obj_set_width( cui_Bar1, 45);
lv_obj_set_height( cui_Bar1, 10);
lv_obj_set_x( cui_Bar1, 213 );
lv_obj_set_y( cui_Bar1, -121 );
lv_obj_set_align( cui_Bar1, LV_ALIGN_CENTER );

lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_BAR1_NUM);
children[UI_COMP_BAR1_BAR1] = cui_Bar1;
lv_obj_add_event_cb(cui_Bar1, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
lv_obj_add_event_cb(cui_Bar1, del_component_child_event_cb, LV_EVENT_DELETE, children);
ui_comp_Bar1_create_hook(cui_Bar1);
return cui_Bar1; 
}

