// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void TopicListCallback(lv_event_t * e);
void topic_select_callback(lv_event_t * e);
void NodeListCallback(lv_event_t * e);
void node_select_callback(lv_event_t * e);
void SearchTopicCallback(lv_event_t * e);
void SearchNodeCallback(lv_event_t * e);
void SubTopicCallback(lv_event_t * e);
void SubNodeNameCallback(lv_event_t * e);
void SubMsgTypeCallback(lv_event_t * e);
void SubTopicNameCallback(lv_event_t * e);
void PubTopicCallback(lv_event_t * e);
void PubNodeNameCallback(lv_event_t * e);
void PubNodeIDCallback(lv_event_t * e);
void PubTopicNameCallback(lv_event_t * e);
void InformationCallback(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
